# Generated by Django 5.1.6 on 2025-05-07 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='joined',
            new_name='date_joined',
        ),
    ]
