# Generated by Django 5.1.6 on 2026-06-21 08:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_helprequest_status_assigned_notes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="helprequest",
            name="legal_issue_type",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="helprequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("in_review", "In review"),
                    ("assigned", "Assigned"),
                    ("resolved", "Resolved"),
                    ("closed", "Closed"),
                ],
                db_index=True,
                default="new",
                max_length=20,
            ),
        ),
    ]
