export const QUERY_KEYS = {
    get_user: 'get_user',
    update_user: 'update_user',
    get_cookies: 'get_cookies',
    login: 'login',
    register: 'register',
    logout: 'logout',
    verify_otp: 'verify_otp',
    resend_otp: 'resend_otp',
    reset_password: 'reset_password',
    reset_password_confirm: 'reset_password_confirm',
    get_users: 'get_users',
    create_user: 'create_user',
    delete_user: 'delete_user',

    get_publications: 'get_publications',
    get_publication: 'get_publication',
    create_publication: 'create_publication',
    update_publication: 'update_publication',
    delete_publication: 'delete_publication',
    get_categories: 'get_categories',
    get_category: 'get_category',
    create_category: 'create_category',
    update_category: 'update_category',
    delete_category: 'delete_category',

    get_help_requests: 'get_help_requests',
    get_help_request: 'get_help_request',
    get_help_request_stats: 'get_help_request_stats',
    create_help_request: 'create_help_request',
    update_help_request: 'update_help_request',
    delete_help_request: 'delete_help_request',
}