# Generated by Django 5.1.6 on 2025-05-08 21:30

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('logo_url', models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()])),
                ('mission_statement', models.TextField()),
                ('vision_statement', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'App Data',
                'verbose_name_plural': 'App Data',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('department', models.CharField(choices=[('clinical', 'Clinical Department'), ('research', 'Research Department'), ('litigation', 'Litigation Department'), ('other', 'Other')], default='other', max_length=20)),
                ('is_previous', models.BooleanField(default=False, help_text='Is this a previous gallery?')),
                ('year', models.PositiveIntegerField(blank=True, help_text='Year of the gallery', null=True)),
                ('ordering', models.PositiveIntegerField(blank=True, help_text='Ordering of the gallery', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Galleries',
                'ordering': ['ordering', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('image', models.URLField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('type', models.CharField(choices=[('person', 'Person'), ('organization', 'Organization')], default='person', max_length=12)),
                ('ordering', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['ordering', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('occupation', models.CharField(max_length=500)),
                ('quote', models.TextField(blank=True, null=True)),
                ('image', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.URLField(null=True, validators=[django.core.validators.URLValidator()])),
                ('instagram', models.URLField(blank=True, null=True)),
                ('x_handle', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('ordering', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app_settings.gallery')),
            ],
            options={
                'verbose_name_plural': 'Gallery Images',
                'ordering': ['ordering', 'gallery__year', 'gallery__title'],
            },
        ),
    ]
