# Generated by Django 5.1.6 on 2025-05-09 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_settings', '0004_galleryimage_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
